"""application_number_sequences

Revision ID: 1a10fde2a385
Revises: b2c3d4e5f6a7
Create Date: 2026-02-25 03:30:40.244378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a10fde2a385'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_number_sequences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institute_id', sa.UUID(), nullable=False),
    sa.Column('academic_year', sa.String(length=10), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('institute_id', 'academic_year', name='uq_institute_year_sequence')
    )
    op.create_index(op.f('ix_application_number_sequences_academic_year'), 'application_number_sequences', ['academic_year'], unique=False)
    op.create_index(op.f('ix_application_number_sequences_institute_id'), 'application_number_sequences', ['institute_id'], unique=False)
    op.create_index('ix_sequence_institute_year', 'application_number_sequences', ['institute_id', 'academic_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sequence_institute_year', table_name='application_number_sequences')
    op.drop_index(op.f('ix_application_number_sequences_institute_id'), table_name='application_number_sequences')
    op.drop_index(op.f('ix_application_number_sequences_academic_year'), table_name='application_number_sequences')
    op.drop_table('application_number_sequences')
    # ### end Alembic commands ###
