"""Initialized Scheme

Revision ID: 200b54038395
Revises: 
Create Date: 2026-01-21 16:49:13.544035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '200b54038395'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('institute_code', sa.String(), nullable=False),
    sa.Column('institute_type', sa.Enum('GOVERNMENT', 'PRIVATE', 'SEMI_GOVERNMENT', name='institutetype'), nullable=False),
    sa.Column('institute_level', sa.Enum('UNIVERSITY', 'COLLEGE', 'INSTITUTE', 'SCHOOL', name='institutelevel'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_APPROVAL', name='institutestatus'), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('regulatory_body', sa.String(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('primary_email', sa.String(), nullable=True),
    sa.Column('primary_phone', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_institutes_institute_code'), 'institutes', ['institute_code'], unique=True)
    op.create_index(op.f('ix_institutes_institute_type'), 'institutes', ['institute_type'], unique=False)
    op.create_index(op.f('ix_institutes_name'), 'institutes', ['name'], unique=False)
    op.create_index(op.f('ix_institutes_status'), 'institutes', ['status'], unique=False)
    op.create_table('campuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institute_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('campus_code', sa.String(), nullable=True),
    sa.Column('campus_type', sa.Enum('BOYS', 'GIRLS', 'CO_ED', name='campustype'), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('province_state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('address_line', sa.String(), nullable=True),
    sa.Column('campus_email', sa.String(), nullable=True),
    sa.Column('campus_phone', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_campuses_campus_type'), 'campuses', ['campus_type'], unique=False)
    op.create_index(op.f('ix_campuses_city'), 'campuses', ['city'], unique=False)
    op.create_index(op.f('ix_campuses_institute_id'), 'campuses', ['institute_id'], unique=False)
    op.create_index(op.f('ix_campuses_province_state'), 'campuses', ['province_state'], unique=False)
    op.create_table('custom_form_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institute_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'TEXTAREA', 'NUMBER', 'EMAIL', 'TEL', 'DATE', 'SELECT', 'RADIO', 'CHECKBOX', 'FILE', name='fieldtype'), nullable=False),
    sa.Column('placeholder', sa.String(), nullable=True),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('default_value', sa.String(), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.Integer(), nullable=True),
    sa.Column('max_value', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('institute_id', 'field_name', name='uq_institute_field_name')
    )
    op.create_index('ix_custom_field_institute_name', 'custom_form_fields', ['institute_id', 'field_name'], unique=False)
    op.create_index(op.f('ix_custom_form_fields_field_name'), 'custom_form_fields', ['field_name'], unique=False)
    op.create_index(op.f('ix_custom_form_fields_institute_id'), 'custom_form_fields', ['institute_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('user', 'super_admin', name='user_role'), nullable=False),
    sa.Column('institute_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_institute_id'), 'users', ['institute_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('admission_calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('academic_year', sa.String(), nullable=False),
    sa.Column('session', sa.Enum('SPRING', 'FALL', 'ANNUAL', 'SUMMER', name='academicsession'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UPCOMING', 'OPEN', 'CLOSED', 'COMPLETED', 'CANCELLED', name='admissioncyclestatus'), nullable=False),
    sa.Column('application_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('application_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_admission_calendars_academic_year'), 'admission_calendars', ['academic_year'], unique=False)
    op.create_index(op.f('ix_admission_calendars_campus_id'), 'admission_calendars', ['campus_id'], unique=False)
    op.create_index(op.f('ix_admission_calendars_status'), 'admission_calendars', ['status'], unique=False)
    op.create_index('ix_calendar_campus_year', 'admission_calendars', ['campus_id', 'academic_year'], unique=False)
    op.create_index('ix_calendar_status_published', 'admission_calendars', ['status', 'is_published'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'code', name='uq_campus_program_code'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_program_campus_code', 'programs', ['campus_id', 'code'], unique=False)
    op.create_index(op.f('ix_programs_campus_id'), 'programs', ['campus_id'], unique=False)
    op.create_index(op.f('ix_programs_category'), 'programs', ['category'], unique=False)
    op.create_index(op.f('ix_programs_code'), 'programs', ['code'], unique=False)
    op.create_index(op.f('ix_programs_level'), 'programs', ['level'], unique=False)
    op.create_index(op.f('ix_programs_name'), 'programs', ['name'], unique=False)
    op.create_table('workflow_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subflow_key', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('bpmn_xml', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('subflow_key', 'version', name='uq_catalog_key_version')
    )
    op.create_index('ix_catalog_key_version', 'workflow_catalog', ['subflow_key', 'version'], unique=False)
    op.create_index(op.f('ix_workflow_catalog_published'), 'workflow_catalog', ['published'], unique=False)
    op.create_index(op.f('ix_workflow_catalog_subflow_key'), 'workflow_catalog', ['subflow_key'], unique=False)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institute_id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('bpmn_xml', sa.Text(), nullable=False),
    sa.Column('subprocess_refs', sa.JSON(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('institute_id', 'process_id', 'version', name='uq_workflow_def_institute_process_version')
    )
    op.create_index('ix_workflow_def_institute_process_version', 'workflow_definitions', ['institute_id', 'process_id', 'version'], unique=False)
    op.create_index('ix_workflow_def_institute_published', 'workflow_definitions', ['institute_id', 'published', 'active'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_institute_id'), 'workflow_definitions', ['institute_id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_published'), 'workflow_definitions', ['published'], unique=False)
    op.create_table('admission_calendar_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admission_cycle_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('seats_filled', sa.Integer(), nullable=False),
    sa.Column('minimum_marks_required', sa.Integer(), nullable=True),
    sa.Column('eligibility_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admission_cycle_id'], ['admission_calendars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_cycle_id', 'program_id', name='uq_cycle_program'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_admission_calendar_programs_admission_cycle_id'), 'admission_calendar_programs', ['admission_cycle_id'], unique=False)
    op.create_index(op.f('ix_admission_calendar_programs_program_id'), 'admission_calendar_programs', ['program_id'], unique=False)
    op.create_index('ix_cycle_program_active', 'admission_calendar_programs', ['admission_cycle_id', 'is_active'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institute_id', sa.UUID(), nullable=False),
    sa.Column('workflow_definition_id', sa.UUID(), nullable=False),
    sa.Column('business_key', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=False),
    sa.Column('state', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_tasks', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_workflow_instance_business_key', 'workflow_instances', ['institute_id', 'business_key'], unique=False)
    op.create_index('ix_workflow_instance_institute_status', 'workflow_instances', ['institute_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_business_key'), 'workflow_instances', ['business_key'], unique=False)
    op.create_index(op.f('ix_workflow_instances_institute_id'), 'workflow_instances', ['institute_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_status'), 'workflow_instances', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_updated_at'), 'workflow_instances', ['updated_at'], unique=False)
    op.create_index(op.f('ix_workflow_instances_workflow_definition_id'), 'workflow_instances', ['workflow_definition_id'], unique=False)
    op.create_table('program_form_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_cycle_id', sa.UUID(), nullable=False),
    sa.Column('form_field_id', sa.UUID(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_field_id'], ['custom_form_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_cycle_id'], ['admission_calendar_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('program_cycle_id', 'form_field_id', name='uq_program_cycle_form_field')
    )
    op.create_index(op.f('ix_program_form_fields_form_field_id'), 'program_form_fields', ['form_field_id'], unique=False)
    op.create_index(op.f('ix_program_form_fields_program_cycle_id'), 'program_form_fields', ['program_cycle_id'], unique=False)
    op.create_table('program_quotas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_cycle_id', sa.UUID(), nullable=False),
    sa.Column('quota_type', sa.Enum('OPEN_MERIT', 'HAFIZ_E_QURAN', 'SPORTS', 'MINORITY', 'DISTRICT_RESERVED', 'SIBLING', 'EMPLOYEE_CHILDREN', 'DISABLED', 'OVERSEAS_PAKISTANI', 'DEFENSE_FORCES', 'CUSTOM', name='quotatype'), nullable=False),
    sa.Column('quota_name', sa.String(), nullable=False),
    sa.Column('allocated_seats', sa.Integer(), nullable=False),
    sa.Column('seats_filled', sa.Integer(), nullable=False),
    sa.Column('eligibility_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('minimum_marks', sa.Integer(), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FILLED', 'SUSPENDED', name='quotastatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_cycle_id'], ['admission_calendar_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('program_cycle_id', 'quota_type', name='uq_program_cycle_quota_type')
    )
    op.create_index(op.f('ix_program_quotas_program_cycle_id'), 'program_quotas', ['program_cycle_id'], unique=False)
    op.create_index(op.f('ix_program_quotas_quota_type'), 'program_quotas', ['quota_type'], unique=False)
    op.create_index('ix_quota_program_cycle_status', 'program_quotas', ['program_cycle_id', 'status'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workflow_instance_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_tokens')
    op.drop_index('ix_quota_program_cycle_status', table_name='program_quotas')
    op.drop_index(op.f('ix_program_quotas_quota_type'), table_name='program_quotas')
    op.drop_index(op.f('ix_program_quotas_program_cycle_id'), table_name='program_quotas')
    op.drop_table('program_quotas')
    op.drop_index(op.f('ix_program_form_fields_program_cycle_id'), table_name='program_form_fields')
    op.drop_index(op.f('ix_program_form_fields_form_field_id'), table_name='program_form_fields')
    op.drop_table('program_form_fields')
    op.drop_index(op.f('ix_workflow_instances_workflow_definition_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_updated_at'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_status'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_institute_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_business_key'), table_name='workflow_instances')
    op.drop_index('ix_workflow_instance_institute_status', table_name='workflow_instances')
    op.drop_index('ix_workflow_instance_business_key', table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index('ix_cycle_program_active', table_name='admission_calendar_programs')
    op.drop_index(op.f('ix_admission_calendar_programs_program_id'), table_name='admission_calendar_programs')
    op.drop_index(op.f('ix_admission_calendar_programs_admission_cycle_id'), table_name='admission_calendar_programs')
    op.drop_table('admission_calendar_programs')
    op.drop_index(op.f('ix_workflow_definitions_published'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_institute_id'), table_name='workflow_definitions')
    op.drop_index('ix_workflow_def_institute_published', table_name='workflow_definitions')
    op.drop_index('ix_workflow_def_institute_process_version', table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_workflow_catalog_subflow_key'), table_name='workflow_catalog')
    op.drop_index(op.f('ix_workflow_catalog_published'), table_name='workflow_catalog')
    op.drop_index('ix_catalog_key_version', table_name='workflow_catalog')
    op.drop_table('workflow_catalog')
    op.drop_index(op.f('ix_programs_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_level'), table_name='programs')
    op.drop_index(op.f('ix_programs_code'), table_name='programs')
    op.drop_index(op.f('ix_programs_category'), table_name='programs')
    op.drop_index(op.f('ix_programs_campus_id'), table_name='programs')
    op.drop_index('ix_program_campus_code', table_name='programs')
    op.drop_table('programs')
    op.drop_index('ix_calendar_status_published', table_name='admission_calendars')
    op.drop_index('ix_calendar_campus_year', table_name='admission_calendars')
    op.drop_index(op.f('ix_admission_calendars_status'), table_name='admission_calendars')
    op.drop_index(op.f('ix_admission_calendars_campus_id'), table_name='admission_calendars')
    op.drop_index(op.f('ix_admission_calendars_academic_year'), table_name='admission_calendars')
    op.drop_table('admission_calendars')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_institute_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_custom_form_fields_institute_id'), table_name='custom_form_fields')
    op.drop_index(op.f('ix_custom_form_fields_field_name'), table_name='custom_form_fields')
    op.drop_index('ix_custom_field_institute_name', table_name='custom_form_fields')
    op.drop_table('custom_form_fields')
    op.drop_index(op.f('ix_campuses_province_state'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_institute_id'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_city'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_campus_type'), table_name='campuses')
    op.drop_table('campuses')
    op.drop_index(op.f('ix_institutes_status'), table_name='institutes')
    op.drop_index(op.f('ix_institutes_name'), table_name='institutes')
    op.drop_index(op.f('ix_institutes_institute_type'), table_name='institutes')
    op.drop_index(op.f('ix_institutes_institute_code'), table_name='institutes')
    op.drop_table('institutes')
    # ### end Alembic commands ###
