"""renamed relationship to guardian_relationship

Revision ID: 537fe662216e
Revises: 9834feea55bf
Create Date: 2026-02-16 23:09:07.730668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '537fe662216e'
down_revision: Union[str, Sequence[str], None] = '9834feea55bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('father_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gendertype'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('identity_doc_number', sa.String(length=15), nullable=False),
    sa.Column('identity_doc_type', sa.Enum('CNIC', 'B_FORM', name='identitydocumenttype'), nullable=False),
    sa.Column('religion', sa.Enum('ISLAM', 'CHRISTIANITY', 'HINDUISM', 'SIKHISM', 'OTHER', name='religiontype'), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('disability_details', sa.Text(), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=False),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('province', sa.Enum('PUNJAB', 'SINDH', 'KPK', 'BALOCHISTAN', 'GILGIT_BALTISTAN', 'AJK', 'ICT', 'FATA', name='provincetype'), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('domicile_province', sa.Enum('PUNJAB', 'SINDH', 'KPK', 'BALOCHISTAN', 'GILGIT_BALTISTAN', 'AJK', 'ICT', 'FATA', name='provincetype'), nullable=False),
    sa.Column('domicile_district', sa.String(length=100), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=False),
    sa.Column('identity_doc_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_student_profile_cnic', 'student_profiles', ['identity_doc_number'], unique=False)
    op.create_index('ix_student_profile_domicile', 'student_profiles', ['domicile_province', 'domicile_district'], unique=False)
    op.create_index('ix_student_profile_location', 'student_profiles', ['city', 'province'], unique=False)
    op.create_index('ix_student_profile_user_id', 'student_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_profiles_city'), 'student_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_student_profiles_domicile_province'), 'student_profiles', ['domicile_province'], unique=False)
    op.create_index(op.f('ix_student_profiles_identity_doc_number'), 'student_profiles', ['identity_doc_number'], unique=True)
    op.create_index(op.f('ix_student_profiles_primary_email'), 'student_profiles', ['primary_email'], unique=False)
    op.create_index(op.f('ix_student_profiles_province'), 'student_profiles', ['province'], unique=False)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('application_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_profile_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('father_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('identity_doc_number', sa.String(length=15), nullable=False),
    sa.Column('identity_doc_type', sa.String(length=20), nullable=False),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('disability_details', sa.Text(), nullable=True),
    sa.Column('primary_email', sa.String(length=255), nullable=False),
    sa.Column('primary_phone', sa.String(length=20), nullable=False),
    sa.Column('alternate_phone', sa.String(length=20), nullable=True),
    sa.Column('street_address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('domicile_province', sa.String(length=50), nullable=False),
    sa.Column('domicile_district', sa.String(length=100), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=False),
    sa.Column('identity_doc_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_profile_id'], ['student_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_application_snapshots_source_profile_id'), 'application_snapshots', ['source_profile_id'], unique=False)
    op.create_index('ix_snapshot_created', 'application_snapshots', ['snapshot_created_at'], unique=False)
    op.create_index('ix_snapshot_source_profile', 'application_snapshots', ['source_profile_id'], unique=False)
    op.create_table('student_academic_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('PRIMARY', 'MIDDLE', 'SECONDARY', 'HIGHER_SECONDARY', name='academiclevel'), nullable=False),
    sa.Column('education_group', sa.Enum('SSC_SCIENCE_BIOLOGY', 'SSC_SCIENCE_COMPUTER', 'SSC_HUMANITIES', 'SSC_COMMERCE', 'SSC_TECHNICAL', 'SSC_AGRICULTURE', 'SSC_HEALTH_SCIENCE', 'HSSC_FSC_PRE_MEDICAL', 'HSSC_FSC_PRE_ENGINEERING', 'HSSC_FSC_GENERAL_SCIENCE', 'HSSC_ICS', 'HSSC_FA', 'HSSC_ICOM', 'HSSC_DCOM', 'HSSC_TECHNICAL', name='educationgroup'), nullable=True),
    sa.Column('institute_name', sa.String(length=255), nullable=False),
    sa.Column('board_name', sa.String(length=100), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('year_of_passing', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('obtained_marks', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('result_card_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('obtained_marks <= total_marks', name='check_marks_valid'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'level', 'board_name', 'roll_number', name='uq_academic_record')
    )
    op.create_index('ix_academic_student_id', 'student_academic_records', ['student_profile_id'], unique=False)
    op.create_index(op.f('ix_student_academic_records_student_profile_id'), 'student_academic_records', ['student_profile_id'], unique=False)
    op.create_table('student_guardians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('guardian_relationship', sa.Enum('FATHER', 'MOTHER', 'BROTHER', 'SISTER', 'UNCLE', 'AUNT', 'GRANDFATHER', 'GRANDMOTHER', 'LEGAL_GUARDIAN', 'OTHER', name='guardianrelationship'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('cnic', sa.String(length=15), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('student_profile_id', 'cnic', name='uq_guardian_student_cnic')
    )
    op.create_index('ix_guardian_student_id', 'student_guardians', ['student_profile_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_student_profile_id'), 'student_guardians', ['student_profile_id'], unique=False)
    op.create_table('application_academic_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('source_academic_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('education_group', sa.String(length=50), nullable=True),
    sa.Column('institute_name', sa.String(length=255), nullable=False),
    sa.Column('board_name', sa.String(length=100), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('year_of_passing', sa.Integer(), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('obtained_marks', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('result_card_url', sa.String(length=500), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_snapshot_id'], ['application_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_academic_id'], ['student_academic_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['staff_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_academic_snapshot_id', 'application_academic_snapshots', ['application_snapshot_id'], unique=False)
    op.create_index('ix_academic_verification_status', 'application_academic_snapshots', ['verification_status'], unique=False)
    op.create_index(op.f('ix_application_academic_snapshots_application_snapshot_id'), 'application_academic_snapshots', ['application_snapshot_id'], unique=False)
    op.create_index(op.f('ix_application_academic_snapshots_verification_status'), 'application_academic_snapshots', ['verification_status'], unique=False)
    op.create_table('application_guardian_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('source_guardian_id', sa.UUID(), nullable=True),
    sa.Column('guardian_relationship', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('cnic', sa.String(length=15), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_snapshot_id'], ['application_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_guardian_id'], ['student_guardians.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_application_guardian_snapshots_application_snapshot_id'), 'application_guardian_snapshots', ['application_snapshot_id'], unique=False)
    op.create_index('ix_guardian_snapshot_id', 'application_guardian_snapshots', ['application_snapshot_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institute_id', sa.UUID(), nullable=False),
    sa.Column('preferred_campus_id', sa.UUID(), nullable=False),
    sa.Column('program_cycle_id', sa.UUID(), nullable=False),
    sa.Column('quota_id', sa.UUID(), nullable=True),
    sa.Column('application_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'DOCUMENTS_PENDING', 'VERIFIED', 'OFFERED', 'REJECTED', 'ACCEPTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('workflow_instance_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('custom_form_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_snapshot_id'], ['application_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_to'], ['staff_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['preferred_campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_cycle_id'], ['program_admission_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quota_id'], ['program_quotas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_snapshot_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_application_assigned', 'applications', ['assigned_to', 'status'], unique=False)
    op.create_index('ix_application_institute_campus_program', 'applications', ['institute_id', 'preferred_campus_id', 'program_cycle_id'], unique=False)
    op.create_index('ix_application_number', 'applications', ['application_number'], unique=False)
    op.create_index('ix_application_status_submitted', 'applications', ['status', 'submitted_at'], unique=False)
    op.create_index('ix_application_student_status', 'applications', ['student_profile_id', 'status'], unique=False)
    op.create_index(op.f('ix_applications_application_number'), 'applications', ['application_number'], unique=True)
    op.create_index(op.f('ix_applications_assigned_to'), 'applications', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_applications_institute_id'), 'applications', ['institute_id'], unique=False)
    op.create_index(op.f('ix_applications_preferred_campus_id'), 'applications', ['preferred_campus_id'], unique=False)
    op.create_index(op.f('ix_applications_program_cycle_id'), 'applications', ['program_cycle_id'], unique=False)
    op.create_index(op.f('ix_applications_quota_id'), 'applications', ['quota_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_student_profile_id'), 'applications', ['student_profile_id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index(op.f('ix_applications_workflow_instance_id'), 'applications', ['workflow_instance_id'], unique=False)
    op.create_table('application_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['staff_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_app_comment_application_created', 'application_comments', ['application_id', 'created_at'], unique=False)
    op.create_index('ix_app_comment_internal', 'application_comments', ['application_id', 'is_internal'], unique=False)
    op.create_index(op.f('ix_application_comments_application_id'), 'application_comments', ['application_id'], unique=False)
    op.create_table('application_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['staff_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['staff_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_documents_verification_status'), 'application_documents', ['verification_status'], unique=False)
    op.create_index('ix_document_application_id', 'application_documents', ['application_id'], unique=False)
    op.create_index('ix_document_verification_status', 'application_documents', ['application_id', 'verification_status'], unique=False)
    op.create_table('application_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'DOCUMENTS_PENDING', 'VERIFIED', 'OFFERED', 'REJECTED', 'ACCEPTED', 'WITHDRAWN', name='applicationstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'DOCUMENTS_PENDING', 'VERIFIED', 'OFFERED', 'REJECTED', 'ACCEPTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_index('ix_status_history_application_created', 'application_status_history', ['application_id', 'created_at'], unique=False)
    op.create_table('student_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_student_comment_application_created', 'student_comments', ['application_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_student_comments_application_id'), 'student_comments', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_comments_application_id'), table_name='student_comments')
    op.drop_index('ix_student_comment_application_created', table_name='student_comments')
    op.drop_table('student_comments')
    op.drop_index('ix_status_history_application_created', table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index('ix_document_verification_status', table_name='application_documents')
    op.drop_index('ix_document_application_id', table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_verification_status'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_application_comments_application_id'), table_name='application_comments')
    op.drop_index('ix_app_comment_internal', table_name='application_comments')
    op.drop_index('ix_app_comment_application_created', table_name='application_comments')
    op.drop_table('application_comments')
    op.drop_index(op.f('ix_applications_workflow_instance_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_student_profile_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_quota_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_program_cycle_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_preferred_campus_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_institute_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_assigned_to'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_number'), table_name='applications')
    op.drop_index('ix_application_student_status', table_name='applications')
    op.drop_index('ix_application_status_submitted', table_name='applications')
    op.drop_index('ix_application_number', table_name='applications')
    op.drop_index('ix_application_institute_campus_program', table_name='applications')
    op.drop_index('ix_application_assigned', table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_guardian_snapshot_id', table_name='application_guardian_snapshots')
    op.drop_index(op.f('ix_application_guardian_snapshots_application_snapshot_id'), table_name='application_guardian_snapshots')
    op.drop_table('application_guardian_snapshots')
    op.drop_index(op.f('ix_application_academic_snapshots_verification_status'), table_name='application_academic_snapshots')
    op.drop_index(op.f('ix_application_academic_snapshots_application_snapshot_id'), table_name='application_academic_snapshots')
    op.drop_index('ix_academic_verification_status', table_name='application_academic_snapshots')
    op.drop_index('ix_academic_snapshot_id', table_name='application_academic_snapshots')
    op.drop_table('application_academic_snapshots')
    op.drop_index(op.f('ix_student_guardians_student_profile_id'), table_name='student_guardians')
    op.drop_index('ix_guardian_student_id', table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_index(op.f('ix_student_academic_records_student_profile_id'), table_name='student_academic_records')
    op.drop_index('ix_academic_student_id', table_name='student_academic_records')
    op.drop_table('student_academic_records')
    op.drop_index('ix_snapshot_source_profile', table_name='application_snapshots')
    op.drop_index('ix_snapshot_created', table_name='application_snapshots')
    op.drop_index(op.f('ix_application_snapshots_source_profile_id'), table_name='application_snapshots')
    op.drop_table('application_snapshots')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_province'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_primary_email'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_identity_doc_number'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_domicile_province'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_city'), table_name='student_profiles')
    op.drop_index('ix_student_profile_user_id', table_name='student_profiles')
    op.drop_index('ix_student_profile_location', table_name='student_profiles')
    op.drop_index('ix_student_profile_domicile', table_name='student_profiles')
    op.drop_index('ix_student_profile_cnic', table_name='student_profiles')
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
