"""removed created by from student profile

Revision ID: 89dfb408ecf4
Revises: 537fe662216e
Create Date: 2026-02-16 23:12:05.933010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89dfb408ecf4'
down_revision: Union[str, Sequence[str], None] = '537fe662216e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'application_academic_snapshots', ['id'])
    op.create_unique_constraint(None, 'application_comments', ['id'])
    op.create_unique_constraint(None, 'application_documents', ['id'])
    op.create_unique_constraint(None, 'application_guardian_snapshots', ['id'])
    op.create_unique_constraint(None, 'application_snapshots', ['id'])
    op.create_unique_constraint(None, 'application_status_history', ['id'])
    op.create_unique_constraint(None, 'applications', ['id'])
    op.create_unique_constraint(None, 'student_academic_records', ['id'])
    op.create_unique_constraint(None, 'student_comments', ['id'])
    op.create_unique_constraint(None, 'student_guardians', ['id'])
    op.create_unique_constraint(None, 'student_profiles', ['id'])
    op.drop_constraint(op.f('student_profiles_created_by_fkey'), 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('student_profiles_created_by_fkey'), 'student_profiles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'student_profiles', type_='unique')
    op.drop_constraint(None, 'student_guardians', type_='unique')
    op.drop_constraint(None, 'student_comments', type_='unique')
    op.drop_constraint(None, 'student_academic_records', type_='unique')
    op.drop_constraint(None, 'applications', type_='unique')
    op.drop_constraint(None, 'application_status_history', type_='unique')
    op.drop_constraint(None, 'application_snapshots', type_='unique')
    op.drop_constraint(None, 'application_guardian_snapshots', type_='unique')
    op.drop_constraint(None, 'application_documents', type_='unique')
    op.drop_constraint(None, 'application_comments', type_='unique')
    op.drop_constraint(None, 'application_academic_snapshots', type_='unique')
    # ### end Alembic commands ###
