"""Workflow schema

Revision ID: 8ccf65e468eb
Revises: efae01f20fdd
Create Date: 2025-11-14 18:40:31.160631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8ccf65e468eb'
down_revision: Union[str, Sequence[str], None] = 'efae01f20fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create user_role enum type
    user_role_enum = postgresql.ENUM('user', 'super_admin', name='user_role')
    user_role_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('institutes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_institutes_name'), 'institutes', ['name'], unique=False)
    op.create_index(op.f('ix_institutes_slug'), 'institutes', ['slug'], unique=True)
    op.create_table('workflow_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subflow_key', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('bpmn_xml', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('subflow_key', 'version', name='uq_catalog_key_version')
    )
    op.create_index('ix_catalog_key_version', 'workflow_catalog', ['subflow_key', 'version'], unique=False)
    op.create_index(op.f('ix_workflow_catalog_published'), 'workflow_catalog', ['published'], unique=False)
    op.create_index(op.f('ix_workflow_catalog_subflow_key'), 'workflow_catalog', ['subflow_key'], unique=False)
    op.create_table('workflow_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('institute_id', sa.UUID(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('workflow_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('bpmn_xml', sa.Text(), nullable=False),
    sa.Column('subprocess_refs', sa.JSON(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('institute_id', 'process_id', 'version', name='uq_workflow_def_institute_process_version')
    )
    op.create_index('ix_workflow_def_institute_process_version', 'workflow_definitions', ['institute_id', 'process_id', 'version'], unique=False)
    op.create_index('ix_workflow_def_institute_published', 'workflow_definitions', ['institute_id', 'published', 'active'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_institute_id'), 'workflow_definitions', ['institute_id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_published'), 'workflow_definitions', ['published'], unique=False)
    op.add_column('users', sa.Column('role', postgresql.ENUM('user', 'super_admin', name='user_role', create_type=False), nullable=False, server_default=sa.text("'user'::user_role")))
    op.add_column('users', sa.Column('institute_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_institute_id'), 'users', ['institute_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(None, 'users', 'institutes', ['institute_id'], ['id'], ondelete='SET NULL')
    op.add_column('workflow_instances', sa.Column('institute_id', sa.UUID(), nullable=False))
    op.add_column('workflow_instances', sa.Column('workflow_definition_id', sa.UUID(), nullable=False))
    op.add_column('workflow_instances', sa.Column('status', sa.String(), nullable=False))
    op.add_column('workflow_instances', sa.Column('current_tasks', sa.JSON(), nullable=True))
    op.add_column('workflow_instances', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('workflow_instances', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_instances', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_workflow_instance_business_key', 'workflow_instances', ['institute_id', 'business_key'], unique=False)
    op.create_index('ix_workflow_instance_institute_status', 'workflow_instances', ['institute_id', 'status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_institute_id'), 'workflow_instances', ['institute_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_status'), 'workflow_instances', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_instances_updated_at'), 'workflow_instances', ['updated_at'], unique=False)
    op.create_index(op.f('ix_workflow_instances_workflow_definition_id'), 'workflow_instances', ['workflow_definition_id'], unique=False)
    op.create_foreign_key(None, 'workflow_instances', 'institutes', ['institute_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflow_instances', 'workflow_definitions', ['workflow_definition_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_instances', type_='foreignkey')
    op.drop_constraint(None, 'workflow_instances', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_instances_workflow_definition_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_updated_at'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_status'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_institute_id'), table_name='workflow_instances')
    op.drop_index('ix_workflow_instance_institute_status', table_name='workflow_instances')
    op.drop_index('ix_workflow_instance_business_key', table_name='workflow_instances')
    op.drop_column('workflow_instances', 'completed_at')
    op.drop_column('workflow_instances', 'updated_at')
    op.drop_column('workflow_instances', 'error_message')
    op.drop_column('workflow_instances', 'current_tasks')
    op.drop_column('workflow_instances', 'status')
    op.drop_column('workflow_instances', 'workflow_definition_id')
    op.drop_column('workflow_instances', 'institute_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_institute_id'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'institute_id')
    op.drop_column('users', 'role')
    # Drop user_role enum type
    op.execute('DROP TYPE IF EXISTS user_role')
    op.drop_index(op.f('ix_workflow_definitions_published'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_institute_id'), table_name='workflow_definitions')
    op.drop_index('ix_workflow_def_institute_published', table_name='workflow_definitions')
    op.drop_index('ix_workflow_def_institute_process_version', table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_workflow_catalog_subflow_key'), table_name='workflow_catalog')
    op.drop_index(op.f('ix_workflow_catalog_published'), table_name='workflow_catalog')
    op.drop_index('ix_catalog_key_version', table_name='workflow_catalog')
    op.drop_table('workflow_catalog')
    op.drop_index(op.f('ix_institutes_slug'), table_name='institutes')
    op.drop_index(op.f('ix_institutes_name'), table_name='institutes')
    op.drop_table('institutes')
    # ### end Alembic commands ###
