"""Application and Student Database structure

Revision ID: 9834feea55bf
Revises: 700378817345
Create Date: 2026-02-16 22:49:01.837635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9834feea55bf'
down_revision: Union[str, Sequence[str], None] = '700378817345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create shifttype enum if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'shifttype') THEN
                CREATE TYPE shifttype AS ENUM ('morning', 'afternoon', 'evening');
            END IF;
        END $$;
    """)
    
    op.create_unique_constraint(None, 'admission_cycles', ['id'])
    op.create_unique_constraint(None, 'campus_admission_cycles', ['id'])
    op.create_unique_constraint(None, 'campus_programs', ['id'])
    op.create_unique_constraint(None, 'campuses', ['id'])
    op.create_unique_constraint(None, 'custom_form_fields', ['id'])
    op.create_unique_constraint(None, 'institutes', ['id'])
    op.create_unique_constraint(None, 'program_admission_cycles', ['id'])
    op.create_unique_constraint(None, 'program_form_fields', ['id'])
    op.create_unique_constraint(None, 'program_quotas', ['id'])
    op.add_column('programs', sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('programs', sa.Column('shift', sa.Enum('morning', 'afternoon', 'evening', name='shifttype', create_type=False), server_default='morning', nullable=False))
    op.create_index(op.f('ix_programs_shift'), 'programs', ['shift'], unique=False)
    op.create_unique_constraint(None, 'programs', ['id'])
    op.create_unique_constraint(None, 'staff_campuses', ['id'])
    op.create_unique_constraint(None, 'staff_profiles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'workflow_catalog', ['id'])
    op.create_unique_constraint(None, 'workflow_definitions', ['id'])
    op.create_unique_constraint(None, 'workflow_instances', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_instances', type_='unique')
    op.drop_constraint(None, 'workflow_definitions', type_='unique')
    op.drop_constraint(None, 'workflow_catalog', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'staff_profiles', type_='unique')
    op.drop_constraint(None, 'staff_campuses', type_='unique')
    op.drop_constraint(None, 'programs', type_='unique')
    op.drop_index(op.f('ix_programs_shift'), table_name='programs')
    op.drop_column('programs', 'shift')
    op.drop_column('programs', 'fee')
    # Note: Not dropping the shifttype enum type as it may be recreated in future migrations
    op.drop_constraint(None, 'program_quotas', type_='unique')
    op.drop_constraint(None, 'program_form_fields', type_='unique')
    op.drop_constraint(None, 'program_admission_cycles', type_='unique')
    op.drop_constraint(None, 'institutes', type_='unique')
    op.drop_constraint(None, 'custom_form_fields', type_='unique')
    op.drop_constraint(None, 'campuses', type_='unique')
    op.drop_constraint(None, 'campus_programs', type_='unique')
    op.drop_constraint(None, 'campus_admission_cycles', type_='unique')
    op.drop_constraint(None, 'admission_cycles', type_='unique')
    # ### end Alembic commands ###
