"""added business key

Revision ID: efae01f20fdd
Revises: 47aa7f70ae61
Create Date: 2025-08-23 16:12:52.785553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efae01f20fdd'
down_revision: Union[str, Sequence[str], None] = '47aa7f70ae61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_instances', sa.Column('business_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_workflow_instances_business_key'), 'workflow_instances', ['business_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_instances_business_key'), table_name='workflow_instances')
    op.drop_column('workflow_instances', 'business_key')
    # ### end Alembic commands ###
